Token
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3ROYW1lIjoiVGhlbyIsImxhc3ROYW1lIjoiTGVvIiwiZW1haWwiOiJ0aGVvQG1pdS5lZHUiLCJpc0FkbWluIjowLCJwaG9uZU51bWJlciI6bnVsbCwiaWF0IjoxNzA3MjM2ODQ4fQ.ZiVdDfbUR9Z7frLRioN2bosK0vKk1pd8QqpzI3ybhwE
Admin Token
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3ROYW1lIjoiVGhlbyIsImxhc3ROYW1lIjoiTGVvIiwiZW1haWwiOiJ0aGVvQG1pdS5lZHUiLCJpc0FkbWluIjoxLCJwaG9uZU51bWJlciI6bnVsbCwiY3JlYXRlZEF0IjoiMjAyNC0wMi0wNlQyMToyNzoyOC4wMDBaIiwibW9kaWZpZWRBdCI6IjIwMjQtMDItMDZUMjE6Mjk6MDkuMDAwWiIsImlhdCI6MTcwNzIzNzAzM30.2EJjW7qIGqd5BiiAZBBk0jg4AeO4EazC9TpTMtFEp5M
###
GET http://localhost:3000/attributes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3ROYW1lIjoiVGhlbyIsImxhc3ROYW1lIjoiTGVvIiwiZW1haWwiOiJ0aGVvQG1pdS5lZHUiLCJpc0FkbWluIjoxLCJwaG9uZU51bWJlciI6bnVsbCwiY3JlYXRlZEF0IjoiMjAyNC0wMi0wNlQyMToyNzoyOC4wMDBaIiwibW9kaWZpZWRBdCI6IjIwMjQtMDItMDZUMjE6Mjk6MDkuMDAwWiIsImlhdCI6MTcwNzIzNzAzM30.2EJjW7qIGqd5BiiAZBBk0jg4AeO4EazC9TpTMtFEp5M
Content-Type: application/json
###
DELETE http://localhost:3000/attributes/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3ROYW1lIjoiVGhlbyIsImxhc3ROYW1lIjoiTGVvIiwiZW1haWwiOiJ0aGVvQG1pdS5lZHUiLCJpc0FkbWluIjoxLCJwaG9uZU51bWJlciI6bnVsbCwiY3JlYXRlZEF0IjoiMjAyNC0wMi0wNlQyMToyNzoyOC4wMDBaIiwibW9kaWZpZWRBdCI6IjIwMjQtMDItMDZUMjE6Mjk6MDkuMDAwWiIsImlhdCI6MTcwNzIzNzAzM30.2EJjW7qIGqd5BiiAZBBk0jg4AeO4EazC9TpTMtFEp5M
###
POST http://localhost:3000/attributes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3ROYW1lIjoiVGhlbyIsImxhc3ROYW1lIjoiTGVvIiwiZW1haWwiOiJ0aGVvQG1pdS5lZHUiLCJpc0FkbWluIjoxLCJwaG9uZU51bWJlciI6bnVsbCwiY3JlYXRlZEF0IjoiMjAyNC0wMi0wNlQyMToyNzoyOC4wMDBaIiwibW9kaWZpZWRBdCI6IjIwMjQtMDItMDZUMjE6Mjk6MDkuMDAwWiIsImlhdCI6MTcwNzIzNzAzM30.2EJjW7qIGqd5BiiAZBBk0jg4AeO4EazC9TpTMtFEp5M
Content-Type: application/json

{
    "name": "clothes sizes",
    "displayName": "size",
    "options": ["xl", "m", "sm"]
}
###
PUT http://localhost:3000/attributes/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZmlyc3ROYW1lIjoiVGhlbyIsImxhc3ROYW1lIjoiTGVvIiwiZW1haWwiOiJ0aGVvQG1pdS5lZHUiLCJpc0FkbWluIjoxLCJwaG9uZU51bWJlciI6bnVsbCwiY3JlYXRlZEF0IjoiMjAyNC0wMi0wNlQyMToyNzoyOC4wMDBaIiwibW9kaWZpZWRBdCI6IjIwMjQtMDItMDZUMjE6Mjk6MDkuMDAwWiIsImlhdCI6MTcwNzIzNzAzM30.2EJjW7qIGqd5BiiAZBBk0jg4AeO4EazC9TpTMtFEp5M
Content-Type: application/json

{
    "name": "clothes sizes",
    "displayName": "size",
    "options": ["xl", "m", "sm", "xxl"]
}