# Fetching the minified node image on apline linux
FROM node:20.12.2

# Declaring env
ENV NODE_ENV development

# Setting up the work directory
WORKDIR /valkyrie
COPY package.json ./
COPY tsconfig.json ./

# Copying all the files in our project
COPY src ./src
RUN ls -a

# Installing dependencies
RUN npm install

# Starting our application
CMD [ "npm", "run", "dev" ]

# Exposing server port
EXPOSE 3000