--#1
CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    firstName VARCHAR(100) NOT NULL,
    lastName VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    companyId INT,
    phoneId INT,
    isAdmin BOOLEAN NOT NULL DEFAULT FALSE,
    discountGroupId INT DEFAULT NULL,
    isEmailVerified BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (companyId) REFERENCES companies(id),
    FOREIGN KEY (phoneId) REFERENCES phone_numbers(id),
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modifiedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

--#2
CREATE TABLE product_categories (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) UNIQUE NOT NULL,
    description TEXT,
    parentId INT,
    imageUrl VARCHAR(255) DEFAULT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modifiedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (parentId) REFERENCES product_categories(id)
);

--#3
CREATE TABLE product_brands (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) UNIQUE NOT NULL,
    description TEXT,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modifiedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

--#4
CREATE TABLE user_addresses (
    id INT PRIMARY KEY AUTO_INCREMENT,
    userId INT NOT NULL,
    street VARCHAR(255) NOT NULL,
    unit VARCHAR(50),
    city VARCHAR(100) NOT NULL,
    state VARCHAR(2) NOT NULL,
    stateId INT NOT NULL,
    zip VARCHAR(5) NOT NULL,
    isBilling BOOLEAN NOT NULL DEFAULT FALSE,
    isPrimary BOOLEAN NOT NULL DEFAULT FALSE,
    isDeletable BOOLEAN NOT NULL DEFAULT TRUE,
    FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (stateId) REFERENCES states(id),
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modifiedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

--#5
CREATE TABLE states (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(70) NOT NULL,
    code VARCHAR(2) NOT NULL
);

--#6
CREATE TABLE product_inventory (
    id INT PRIMARY KEY AUTO_INCREMENT,
    quantity INT NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modifiedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
);

--#7
CREATE TABLE companies (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    typeId INT NOT NULL,
    sizeId INT NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modifiedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deletedAt TIMESTAMP NULL DEFAULT NULL,
    FOREIGN KEY (typeId) REFERENCES company_types(id),
    FOREIGN KEY (sizeId) REFERENCES company_sizes(id)
);

---#8
CREATE TABLE company_types (
    id INT PRIMARY KEY AUTO_INCREMENT,
    type VARCHAR(50) NOT NULL
);

---#9
CREATE TABLE company_sizes (
    id INT PRIMARY KEY AUTO_INCREMENT,
    size VARCHAR(10) NOT NULL
);

---#10
CREATE TABLE phone_numbers (
    id INT PRIMARY KEY AUTO_INCREMENT,
    phoneNumber VARCHAR(15) NOT NULL,
    userId INT NOT NULL,
    companyId INT,
    isPhoneVerified BOOLEAN NOT NULL DEFAULT FALSE,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modifiedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deletedAt TIMESTAMP NULL DEFAULT NULL,
    FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (companyId) REFERENCES companies(id)
);

---#11
CREATE TABLE email_verifications (
    id INT PRIMARY KEY AUTO_INCREMENT,
    token VARCHAR(50) NOT NULL,
    userId INT NOT NULL,
    FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);

---#12
CREATE TABLE phone_verifications (
    id INT PRIMARY KEY AUTO_INCREMENT,
    token VARCHAR(50) NOT NULL,
    userId INT NOT NULL,
    FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE
);

---#13
CREATE TABLE discount_groups (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) UNIQUE NOT NULL,
    ranking INT NOT NULL DEFAULT 0,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modifiedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
);

---#14
CREATE TABLE discounts (
    id INT PRIMARY KEY AUTO_INCREMENT,
    discountGroupId INT DEFAULT NULL,
    name VARCHAR(255) NOT NULL,
    percentage DECIMAL(5, 2) NOT NULL,
    isActive BOOLEAN NOT NULL DEFAULT FALSE,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modifiedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (discountGroupId) REFERENCES discount_groups(id)
);

---#15
CREATE TABLE product_attributes (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    displayName VARCHAR(255) NOT NULL,
    options JSON,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modifiedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

---#16
CREATE TABLE products (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    specifications TEXT,
    categoryId INT NOT NULL,
    brandId INT NOT NULL,
    inventoryId INT NOT NULL,
    isActive BOOLEAN NOT NULL DEFAULT TRUE,
    isNew BOOLEAN NOT NULL DEFAULT TRUE,
    isSponsored BOOLEAN NOT NULL DEFAULT FALSE,
    imageUrls JSON,
    attributesIds JSON,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modifiedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deletedAt TIMESTAMP NULL DEFAULT NULL,
    FOREIGN KEY (categoryId) REFERENCES product_categories(id) ON DELETE CASCADE,
    FOREIGN KEY (brandId) REFERENCES product_brands(id) ON DELETE CASCADE,
    FOREIGN KEY (inventoryId) REFERENCES product_inventory(id) ON DELETE CASCADE
);

---#17
CREATE TABLE reviews (
    id INT PRIMARY KEY AUTO_INCREMENT,
    productId INT NOT NULL,
    userId INT NOT NULL,
    rating INT NOT NULL,
    comment TEXT,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modifiedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deletedAt TIMESTAMP NULL DEFAULT NULL,
    FOREIGN KEY (productId) REFERENCES products(id),
    FOREIGN KEY (userId) REFERENCES users(id)
);