POST http://localhost:3000/auth/sign-up
Content-Type: application/json

{
    "firstName": "theo",
    "lastName": "leO",
    "email": "tHEo@miu.edu",
    "password": "123456"
}
###
POST http://localhost:3000/auth/sign-up
Content-Type: application/json

{
    "firstName": "theo",
    "lastName": "leO",
    "email": "mohamed_sarhan@gmail.com",
    "password": "123456",
    "company": {
        "name": "Phoenix",
        "typeId": 1,
        "sizeId": 1
    }
}
###
POST http://localhost:3000/auth/sign-in
Content-Type: application/json
{
    "email": "tHEooo@miu.edu",
    "password": "123456"
}